using UnityEngine;

// เนื้อหาไทย/อังกฤษอิงปุ่มและกลไกในโปรเจกต์ ข้อมูลถูกบันทึกลง prefab เพื่อแก้ใน Inspector ได้
public static class GameHelpContent
{
    static readonly Color Cyan=new Color32(130,231,242,255),Gold=new Color32(255,209,111,255),Red=new Color32(255,148,158,255),Green=new Color32(150,226,179,255);
    static GameHelpWindow.Copy T(string th,string en)=>new GameHelpWindow.Copy{thai=th,english=en};
    static GameHelpWindow.Section S(string th,string en,string bodyTh,string bodyEn,Color color)=>new GameHelpWindow.Section{heading=T(th,en),body=T(bodyTh,bodyEn),accent=color};
    static GameHelpWindow.Page P(string tabTh,string tabEn,string titleTh,string titleEn,string hintTh,string hintEn,params GameHelpWindow.Section[] sections)=>new GameHelpWindow.Page{tab=T(tabTh,tabEn),title=T(titleTh,titleEn),summary=T(hintTh,hintEn),sections=sections};
    public static GameHelpWindow.Page[] Create()=>new[]{
        P("เริ่มต้น","Getting started","ก่อนก้าวเข้าสู่รอยแยก","Before entering the Rift","อ่านได้ทุกเมื่อด้วยปุ่ม ? หรือ F1","Open this guide anytime with ? or F1",
            S("01  เลือกฮีโร่","01  Choose your hero","ดูเลือด พลังงาน และสกิล Q / E บนหน้าเลือกตัวละคร\nแต่ละอาชีพมีอาวุธเริ่มต้นและสไตล์การต่อสู้ต่างกัน","Review HP, energy and Q / E skills on the hero screen.\nEach class has its own starting weapon and combat style.",Cyan),
            S("02  สำรวจและเตรียมตัว","02  Explore and prepare","เข้าห้อง กำจัดศัตรู เก็บเงินและไอเท็ม\nแวะร้านค้าเพื่อซื้ออาวุธ ยา หรือบัพก่อนเจอบอส","Enter rooms, defeat enemies and collect coins and items.\nVisit shops for weapons, potions or buffs before a boss.",Gold),
            S("03  เอาตัวรอดให้ถึงบอส","03  Survive the encounter","เคลื่อนที่หลบการโจมตี และสังเกตสัญญาณเตือนบนพื้น\nเลือดหมดคือจบรอบ เริ่มเกมใหม่จะรีเซ็ตพรและบัพของรอบนั้น","Keep moving and watch for warning areas on the floor.\nAt zero HP the run ends. A new run resets blessings and buffs.",Red)),
        P("ปุ่มควบคุม","Controls","ควบคุมฮีโร่ของคุณ","Control your hero","คีย์บอร์ดสำหรับเคลื่อนที่ · เมาส์สำหรับเล็ง","Move with the keyboard · Aim with the mouse",
            S("W A S D / ลูกศร  ·  เคลื่อนที่","W A S D / Arrow keys  ·  Move","กดปุ่มทิศทางเพื่อเดิน  ·  กด Shift ค้างเพื่อวิ่ง\nเลื่อนเมาส์เพื่อหันอาวุธไปยังเป้าหมาย","Use direction keys to move. Hold Shift to run.\nMove the mouse to aim your weapon.",Cyan),
            S("คลิกซ้าย  ·  โจมตี     Q / E  ·  สกิล","Left mouse  ·  Attack     Q / E  ·  Skills","ธนู: กดค้างเพื่อง้าง ปล่อยเพื่อยิง\nดูพลังงานที่ต้องใช้และคูลดาวน์ก่อนกดสกิลซ้ำ","Bow: hold to draw, then release to fire.\nCheck your energy and skill cooldowns before using them again.",Gold),
            S("F  ·  ใช้งาน     R  ·  สลับอาวุธ","F  ·  Interact     R  ·  Swap weapon","F ใช้เก็บอาวุธ เปิดร้าน หรือใช้วาร์ปเมื่ออยู่ใกล้\nR สลับอาวุธสองช่อง  ·  Esc หยุดเกม  ·  F1 เปิด/ปิดคู่มือ","Use F near a weapon, shop or portal. R swaps weapon slots.\nEsc pauses the game. F1 opens or closes this guide.",Green)),
        P("อาวุธและระดับ","Weapons & rarity","รู้จักอาวุธและสีระดับ","Weapons and rarity","สีช่วยบอกระดับ แต่ควรอ่านความสามารถของอาวุธด้วย","Color shows rarity; special abilities matter too",
            S("สีขาว  ·  เริ่มต้น / ทั่วไป","White  ·  Starter / Common","อาวุธเริ่มต้นติดมากับฮีโร่ อาวุธทั่วไปพบได้ระหว่างเล่น\nถือได้สองชิ้น หากเต็ม การเก็บชิ้นใหม่จะแทนชิ้นที่กำลังถือ","Heroes begin with a starting weapon. Common weapons appear in runs.\nCarry two weapons; a new pickup replaces the active one if both slots are full.",new Color32(235,232,244,255)),
            S("สีฟ้า  ·  หายาก","Blue  ·  Rare","อาวุธหายากมีลักษณะหรือความสามารถต่างจากอาวุธทั่วไป\nดูค่าดาเมจ ความเร็วโจมตี และพลังงานประกอบการเลือก","Rare weapons offer different stats or abilities.\nCompare damage, attack speed and energy cost when choosing.",Cyan),
            S("สีทอง  ·  ตำนาน","Gold  ·  Legendary","อาวุธตำนานมีความสามารถพิเศษตามชนิด\nตัวอย่าง: ค้อนระดับทองกดค้างชาร์จ แล้วปล่อยเพื่อทุบวงกว้าง","Legendary weapons have special abilities.\nFor example, hold then release a gold hammer for a wide charged slam.",Gold)),
        P("เลือดและพลังงาน","HP & energy","ดูแลทรัพยากรของคุณ","Manage your resources","หลอดเลือดและพลังงานอยู่มุมซ้ายบน","HP and energy bars are at the top left",
            S("เลือด  ·  แถบสีแดง","HP  ·  Red bar","ศัตรูและกับดักทำให้เสียเลือด เมื่อเหลือศูนย์จะจบรอบ\nขวดยาเลือดฟื้นฟูได้ไม่เกินเลือดสูงสุด","Enemies and traps deal damage. Zero HP ends the run.\nHealth potions restore HP up to your maximum.",Red),
            S("พลังงาน  ·  แถบสีฟ้า","Energy  ·  Blue bar","อาวุธและสกิลบางชนิดใช้พลังงาน ถ้าไม่พอจะใช้ไม่ได้\nเลขบนช่องอาวุธบอกพลังงานที่ใช้ต่อการโจมตี","Some weapons and skills require energy and cannot fire without enough.\nThe number on the weapon slot shows its energy cost.",Cyan),
            S("เก็บขวดยาเมื่อจำเป็น","Pick up potions when needed","เดินเข้าใกล้เหรียญและขวดยาเพื่อเก็บ\nถ้าเลือดหรือพลังงานเต็ม ขวดชนิดนั้นจะอยู่บนพื้นให้เก็บภายหลัง","Walk near coins and potions to collect them.\nA potion stays on the ground when its matching resource is full.",Green)),
        P("ร้านค้าและบัพ","Shops & buffs","ซื้อของให้เข้ากับการเล่น","Shop for your build","เดินเข้าใกล้ร้านแล้วกด F หรือคลิกที่ร้าน","Move near a shop and press F, or click the shop",
            S("ร้านอาวุธและขวดยา","Weapons and potions","ร้านมีขวดยาเลือด ขวดยาพลังงาน และอาวุธสุ่ม\nดูเงินและราคา แล้วคลิกปุ่มราคาเพื่อซื้อสินค้าชิ้นนั้น","Shops stock health potions, energy potions and random weapons.\nCheck your coins and click an item's price to buy it.",Cyan),
            S("ร้านสีแดง  ·  บัพประจำรอบ","Red shop  ·  Run buffs","เลือกรับบัพเพิ่มเลือดสูงสุด พลังงานสูงสุด หรือดาเมจ\nมีผลจนจบรอบการเล่น และรีเซ็ตเมื่อเริ่มเกมใหม่","Buy bonuses to maximum HP, maximum energy or damage.\nThese bonuses last for the current run and reset on a new game.",Red),
            S("อ่านข้อเสียก่อนซื้อ","Read the trade-off before buying","ร้านบัพมีสี่ข้อเสนอ หนึ่งข้อให้ผลแรงแต่มีข้อเสีย\nเช่น เพิ่มดาเมจมากแต่ลดเลือดสูงสุด ข้อเสียมีผลทันที","The buff shop has four offers, including one strong bonus with a drawback.\nFor example, extra damage may reduce maximum HP immediately.",Gold)),
        P("พรควอนตัม","Blessings","เลือกพรให้เสริมกัน","Combine your blessings","พรจากการผ่านด่านแยกจากบัพที่ซื้อในร้าน","Stage-clear blessings are separate from shop buffs",
            S("เลือกหนึ่งจากสาม","Choose one of three","เมื่อถึงจุดเลือกพร เกมจะหยุดให้เลือกจากการ์ดที่สุ่มมา\nอ่านผลของแต่ละใบ แล้วเลือกให้เหมาะกับอาวุธที่ใช้","At blessing selection, the game pauses and offers random cards.\nRead each effect and choose one that fits your weapon.",Cyan),
            S("สะสมได้สูงสุดสี่พร","Keep up to four blessings","พรที่มีแล้วสามารถอัปเกรดได้ถึงระดับสาม\nเมื่อช่องเต็มจะเน้นอัปเกรดพรเดิม แทนการเพิ่มชนิดใหม่","Collect up to four distinct blessings and upgrade them to level three.\nWhen slots are full, offers upgrade existing blessings instead.",Gold),
            S("เริ่มรอบใหม่ เลือกแนวทางใหม่","A new run, a new build","พรมีผลตามเงื่อนไขของแต่ละใบ เช่น ฟันลบกระสุน\nดูพรที่ได้จากไอคอนบน HUD พรจะรีเซ็ตเมื่อเริ่มเกมใหม่","Effects have their own conditions, such as clearing bullets with a slash.\nYour HUD shows owned blessings. All reset on a new run.",Green)),
        P("ห้องและมินิแมพ","Rooms & minimap","สำรวจเส้นทางของด่าน","Find your way through a stage","มินิแมพอยู่มุมขวาบนใต้จำนวนเงิน","The minimap sits below your coins at the top right",
            S("?  ห้องที่ยังไม่สำรวจ","?  Unvisited room","เส้นเชื่อมในมินิแมพแสดงทางระหว่างห้อง\nห้องที่เคยเข้าแล้วจะเปลี่ยนสถานะให้แยกจากห้องที่ยังไม่เข้า","Connections show paths between rooms.\nVisited rooms look different from rooms you have not entered.",Cyan),
            S("ประตูปิดระหว่างต่อสู้","Combat locks the doors","ห้องต่อสู้จะกั้นประตูจนกว่าจะกำจัดศัตรูครบตามเงื่อนไข\nสังเกตวัตถุทำลายได้ ซึ่งอาจให้ขวดยาฟื้นฟู","Combat rooms keep doors shut until their enemies are cleared.\nBreakable objects may drop healing or energy potions.",Gold),
            S("ไอคอนวาร์ป  ·  ทางไปด่านถัดไป","Portal icon  ·  Next stage","หลังพบห้องวาร์ป มินิแมพจะแสดงไอคอนประตูมิติ\nเคลียร์ห้องที่เฝ้าวาร์ป แล้วเข้าใกล้กด F เพื่อเดินทางต่อ","After discovering the exit room, its portal icon appears on the minimap.\nClear its guards, approach the portal and press F to continue.",Green)),
        P("กับดักและบอส","Traps & bosses","ดูสัญญาณก่อนอันตราย","Read the warning signs","การหลบและเลือกจังหวะสำคัญพอ ๆ กับดาเมจ","Positioning and timing matter as much as damage",
            S("ซากยาน  ·  รอยแยกและหนาม","Shipwreck  ·  Rifts and spikes","หลบรอยแยกสีม่วงที่ดึงผู้เล่น และระวังพื้นหนาม\nหนามทำงานเป็นรอบ มีสัญญาณเตือนก่อนพุ่งขึ้น","Avoid purple rifts that pull you in, and watch for spike tiles.\nSpikes activate in cycles and warn before rising.",Cyan),
            S("ป่ามิติ  ·  เถาวัลย์พิษ","Dimensional forest  ·  Poison vines","ออกจากพื้นที่เตือนก่อนเถาวัลย์โจมตี\nพิษทำให้เสียเลือดต่อเนื่องชั่วคราว ระวังเลือดระหว่างหลบ","Leave warning areas before the vines strike.\nPoison drains HP over time for a limited duration.",Green),
            S("บอส  ·  เปลี่ยนจังหวะตามเฟส","Bosses  ·  Watch for phase changes","สังเกตท่าเตรียมโจมตีและหลอดเลือดบอส\nบอสบางตัวเปลี่ยนท่าหรือเปิดพื้นอันตรายเมื่อเปลี่ยนเฟส","Watch attack wind-ups and the boss health bar.\nSome bosses change attacks or activate floor hazards in later phases.",Red))
    };
}
